### ISSUE TITLE
timestamp应该是string

### ISSUE THREAD

**Issue by Diluka** [OtkurBiz/wechat-payment-node#12]
微信支付文档
https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=5

**Comment by MirGhojam** [comment]
App支付的timeStamp确实是Int，谢谢指出 @Diluka

**Comment by Diluka** [comment]
@MirGhojam App支付没错，是微信搞了两套签名，我看的这个是小程序的，希望能加上一个小程序签名
