### ISSUE TITLE
这是什么东西？出错了

### ISSUE THREAD

**Issue by Diluka** [OtkurBiz/wechat-payment-node#15]
这个req有定义么？全局变量，赋值的意义何在？没有什么地方读取过
https://github.com/OtkurBiz/wechat-payment-node/blob/de2d596e185e93c824897be78afbb20bf237a9b7/src/WechatPayment.js#L294

**Comment by MirGhojam** [comment]
谢谢你一直以来的支持， 问题已修复 @Diluka
