### ISSUE TITLE
wxCallback is not a function

### ISSUE THREAD

**Issue by thinkive** [OtkurBiz/wechat-payment-node#3]
router.use('/wechat/payment/notify', wechatPaymentInstance.wxCallback(function(notification, req, res, next){
  // 处理商户业务逻辑

  // res.success() 向微信返回处理成功信息，res.fail()返回失败信息。
  res.success();
})); 报错。没有wxCallback这个方法

**Comment by boyaq** [comment]
不应该啊，你的wechatPaymentInstance是不是没有引用成功啊

**Comment by hudaqiang** [comment]
App ( trade_type: 'APP' )支付之后返回SUCCESS ,但是返回的签名不正确,不能调起微信支付

**Comment by Pana** [comment]
我这也报这个错

**Comment by Pana** [comment]
刚看了下代码, 他文档写错了, 回调这里不应该用 wechatPaymentInstance 而是用 WechatPayment
wxCallback 是一个类方法

**Comment by boyaq** [comment]
@Pana is right! it's static method. 文档有误，已改正。那确实是个静态方法
