### ISSUE TITLE
微信APP支付回调接口没处理好

### ISSUE THREAD

**Issue by wsd1** [OtkurBiz/wechat-payment-node#9]
代码写的挺好的 是我喜欢的ES7 风格，不过填坑花了几个小时：

https://github.com/OtkurBiz/wechat-payment-node/blob/525f60ed9edbd2f71e03771bd44e748f1fe06a78/src/WechatPayment.js#L311

utils.pipe(req, function (err, data) {
改为
utils.pipe(req, async function (err, data) {

https://github.com/OtkurBiz/wechat-payment-node/blob/525f60ed9edbd2f71e03771bd44e748f1fe06a78/src/WechatPayment.js#L313

let notification = WechatPayment.checkNotification(notification, apiKey, type);
改为：
let notification = await WechatPayment.checkNotification(xml, apiKey, type);

亲测。

**Comment by MirGhojam** [comment]
@wsd1 😆， 那天发布的有点仓促， 谢谢你的改正。
